import { readFile, stat } from "node:fs/promises";
import { join, normalize, resolve } from "node:path";
import { NextResponse } from "next/server";
import { getUploadDir, MAX_FILE_SIZE } from "@/lib/upload";

/**
 * Serves uploaded images from the Railway Volume at /uploads/<filename>.
 *
 * `next.config.ts` rewrites cannot target the filesystem — only routes —
 * so this catch-all route handler reads files from the volume mount
 * (UPLOAD_DIR, default public/uploads in dev where they're served
 * statically) and streams them back with long-lived cache headers.
 *
 * Filenames are always `<uuid>.<ext>` generated by saveUpload(), but we
 * still normalize + confine paths to the upload dir as defense in depth
 * against traversal.
 */

const MIME_BY_EXT: Record<string, string> = {
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".png": "image/png",
  ".webp": "image/webp",
  ".avif": "image/avif",
};

export async function GET(
  _request: Request,
  { params }: { params: Promise<{ path: string[] }> },
): Promise<NextResponse> {
  const { path: segments } = await params;

  // Confine to the upload directory: reject any path that escapes it.
  const uploadRoot = resolve(getUploadDir());
  const requested = resolve(
    uploadRoot,
    join(...segments.map((s) => normalize(s))),
  );
  if (!requested.startsWith(uploadRoot + "/")) {
    return new NextResponse("Not found", { status: 404 });
  }

  let data: Buffer;
  try {
    const info = await stat(requested);
    if (!info.isFile() || info.size > MAX_FILE_SIZE) {
      return new NextResponse("Not found", { status: 404 });
    }
    data = await readFile(requested);
  } catch {
    return new NextResponse("Not found", { status: 404 });
  }

  const ext = requested.slice(requested.lastIndexOf(".")).toLowerCase();
  const mime = MIME_BY_EXT[ext] ?? "application/octet-stream";

  return new NextResponse(new Uint8Array(data), {
    status: 200,
    headers: {
      "Content-Type": mime,
      "Content-Length": String(data.byteLength),
      "Cache-Control": "public, max-age=31536000, immutable",
    },
  });
}